"""add mfa 

Revision ID: edc5adf96295
Revises: 
Create Date: 2026-03-17 05:11:17.187381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edc5adf96295'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
        # batch_op.alter_column('password_hash',
        #        existing_type=mysql.VARCHAR(length=255),
        #        type_=sa.String(length=128),
        #        existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('totp_secret')

    with op.batch_alter_table('admin_accounts', schema=None) as batch_op:
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('totp_secret')

    # ### end Alembic commands ###
